apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
  namespace: iicpc-telemetry
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: iicpc
  PG_URL: "postgres://postgres:postgres@timescaledb.iicpc-telemetry.svc.cluster.local:5432/iicpc?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
  namespace: iicpc-frontend  # 🚀 Added for your frontend API to consume!
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: iicpc
  PG_URL: "postgres://postgres:postgres@timescaledb.iicpc-telemetry.svc.cluster.local:5432/iicpc?sslmode=disable"